name:                hs-music
version:             0.1.0.0
github:              "ssipos90/hs-music"
license:             BSD3
author:              "Sebastian Sipos"
maintainer:          "sebastiansipos90@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ssipos90/hs-music#readme>

dependencies:
- base >= 4.7 && < 5
- HsYAML >= 0.2.1.0 && < 0.2.2
- bytestring >= 0.10.8.2 && < 0.10.9
- directory >= 1.3.3.0 && < 1.3.4
- text >= 1.2.3.1 && < 1.2.4
- process >= 1.6.5.0 && < 1.6.6
- protolude >= 0.2.3 && < 0.2.4
- url >= 2.1.3 && < 2.1.4

library:
  source-dirs: src

default-extensions:  NoImplicitPrelude
                  , OverloadedStrings
executables:
  hs-music-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-music

tests:
  hs-music-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-music
